### ISSUE TITLE
Switch to Github app model (bumps should only write to 1 file)

### ISSUE THREAD

**Issue by armenzg** [getsentry/gitbot#19]
CC @BYK @billyvg Let me know if this makes sense to you. I don't think we risk is too high to make it worth working on this but I would like to at least document it.

If bumping `getsentry` required only touching 1 file and we switched to a GH app, we would remove the security risk of leaking an SSH key from the getsentry bot. The key being misused would mean that the individual would be able to commit code (or checkout private repo code) anywhere that the bot can.

This screenshot shows the [1-file permission](https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-single-file):
<img width="748" alt="image" src="https://user-images.githubusercontent.com/44410/118034271-cc793200-b337-11eb-91fa-f1e0a4914a3c.png">

We would not need to give [contents access](https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents).
<img width="745" alt="image" src="https://user-images.githubusercontent.com/44410/118034899-840e4400-b338-11eb-90cb-f11e07e7ae34.png">

**Comment by asottile-sentry** [comment]
we're sunsetting gitbot -- closing all issues
