### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by armenzg** [getsentry/gitbot#31]
CC @billyvg 

I don't think there's anything to do at the moment but I would like to keep track of it.

Once in [ancient history](https://github.com/armenzg/mozilla_ci_tools/commit/ab0bd90a1f2dc909ccdc4e5f6586623125967446), I remember `json` was giving us trouble with memory usage and we use `ijson` instead.
I wonder what tools there are out there to keep track of memory leaks.

The memory usage for the production instance sky rocketed, terminated and recuperated. No outage from it. The staging instance did not see the same issue and stayed around 20% usage. No issues on Sentry during the last 24 hours.

![image](https://user-images.githubusercontent.com/44410/120801410-f87e7200-c4f5-11eb-82df-c789262d2d49.png)

From Anton:
Things to keep in mind usually:
* Does your web processes restart after X number of requests (e.g. uwsgi can do that)
* Do you have any metrics about the number of requests that were handled at the time? Maybe there was a traffic surge?
In any case, it’s too difficult to say what might be wrong without any additional context, sorry \:

**Comment by asottile-sentry** [comment]
we're sunsetting gitbot -- closing all issues
