### ISSUE TITLE
Calling run should show the output live

### ISSUE THREAD

**Issue by armenzg** [getsentry/gitbot#46]
When calling `subprocess.run` if we capture the output it will get reported to Sentry, however, it will not show up in the console and make it look like nothing is happening. If we don't capture it, it will not be reported properly to Sentry.

Let's change the code to capture *and* to show up on stdout live.

e.g. https://stackoverflow.com/questions/18421757/live-output-from-subprocess-command

**Comment by asottile-sentry** [comment]
we're sunsetting gitbot -- closing all issues
