### ISSUE TITLE
Use traces_sampler instead of traces_sample_rate

### ISSUE THREAD

**Issue by armenzg** [getsentry/gitbot#58]
Right now we ingest 100% of all performance data.
All transactions that take less than 100ms are events that we ignore. Over 90% of our events are to be ignored and I don't want their performance data as it makes it hard to navigate.

Docs about `traces_sampler`:
https://docs.sentry.io/platforms/python/performance/

**Comment by asottile-sentry** [comment]
we're sunsetting gitbot -- closing all issues
