### ISSUE TITLE
Commits close to each other cause a bump version conflict & memory increase on production

### ISSUE THREAD

**Issue by armenzg** [getsentry/gitbot#66]
There was a Sentry release and 3 commits were pushed [1].
The last two were at the same time, thus, I assume the GH events that came to the app were received almost at the same time [2].
One was at `Sun Aug 15 17:20:58 2021 +0000` and the previous one was at `Sun Aug 15 17:20:47 2021 +0000`. That's 11 seconds apart.

It seems that staging managed to process the last two commits properly [3].

All of this created this [error](https://sentry.io/organizations/sentry/issues/2578072535/?project=5748916&query=is%3Aunresolved) in Sentry:
```
From https://github.com/getsentry/getsentry
 * branch            master     -> FETCH_HEAD
   faadd81..362f126  master     -> origin/master
First, rewinding head to replay your work on top of it...
Applying: getsentry/sentry@c8077ba9c2f7fd625e3affaae99bec94360532f8
Using index info to reconstruct a base tree...
M	cloudbuild.yaml
M	docker/frontend_cloudbuild.yaml
M	requirements-sentry.txt
Falling back to patching base and 3-way merge...
Auto-merging requirements-sentry.txt
CONFLICT (content): Merge conflic...
```

This is what happened:
```shell
13:21:01 git clone --depth 1 -b master https://getsentry-bot:[Filtered]@github.com/getsentry/getsentry /tmp/tmpktdmt0ip
13:21:04 the call to bump-sentry
13:21:05 This commit is created "[master dcf2c6b] getsentry/sentry@c8077ba9c2f7fd625e3affaae99bec94360532f8"
13:21:05 the push fails > git push origin master (cwd: /tmp/tmpktdmt0ip)
13:21:05 Attempt to rebase fails > git pull --rebase origin master (cwd: /tmp/tmpktdmt0ip)
```

The code did not try 5 times to push and the git pull rebase does not do the trick.

This could be resolved by trying having two different checkouts and trying to produce a race condition to determine the recovery.

For now, I have made both GCR apps to only have 1 instance running at a time even though I think even 1 instance could get into this state if more than 1 request is being handled at the same time.

[1]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/44410/129733719-14e63f1d-a4a8-4d6d-9074-cea0748a9803.png">
[2]
<img width="162" alt="image" src="https://user-images.githubusercontent.com/44410/129733876-157f95c1-c1e7-47a0-a21f-907dd09386d8.png">

[3] Screenshot from getsentry-test-repo:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/44410/129734250-225ef917-e7f3-4e48-8efe-811782b4cfa3.png">

**Comment by asottile-sentry** [comment]
we're sunsetting gitbot -- closing all issues
