### ISSUE TITLE
Prevent test-branch issues

### ISSUE THREAD

**Issue by armenzg** [getsentry/gitbot#76]
CC: @billyvg 

I see that billy landed commits in `test-branch` on the `sentry` repo [1]. Unfortunately, that created commits on the real `getsentry` repo [2].

The problem is that we always bump on `master` (`GETSENTRY_BRANCH`). https://github.com/getsentry/gitbot/blob/92b98f05cb4a2a458f68084f9d785a8f5e397d44/gitbot/deployhook.py#L116-L118

Using `test-branch` was useful when doing development during staging but I never tried it once we went live.

We should probably add a test for this and see if we can extract the branch for the push from here: https://github.com/getsentry/gitbot/blob/92b98f05cb4a2a458f68084f9d785a8f5e397d44/gitbot/deployhook.py#L94-L97

[1]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/44410/135097354-25bed452-7f74-4cb2-a2f5-e904c422751f.png">

[2]
<img width="425" alt="image" src="https://user-images.githubusercontent.com/44410/135097291-1c7be229-99e4-4f21-9927-57781127ddf9.png">

**Comment by asottile-sentry** [comment]
we're sunsetting gitbot -- closing all issues
