### ISSUE TITLE
Bump frontend version on sync

### ISSUE THREAD

**Issue by billyvg** [getsentry/gitbot#80]
It would be nice if we could use calver on our [frontend Sentry releases](https://sentry.io/organizations/sentry/releases/) -- we currently use it for [backend releases](https://sentry.io/organizations/sentry/releases/backend%4022.5.0%2Bedf0dec5d735e290a64ed61d450cf64a3bf46978/?project=1) but [not frontend](https://sentry.io/organizations/sentry/releases/frontend%40edf0dec5d735e290a64ed61d450cf64a3bf46978/?project=11276).

**Comment by asottile-sentry** [comment]
we're sunsetting gitbot -- closing all issues
